/**
 * worker.js - Web Worker for LLM inference
 * 
 * SKZ Autonomous Agents Integration
 * OJSkin - Open Journal Systems with Skin Zone Journal
 * 
 * Runs WASM inference in a separate thread to keep UI responsive.
 * Zero tolerance for mock implementations - production quality only.
 */

// Import WASM module (generated by Emscripten)
importScripts('llama-tiny.js');

let Module = null;
let model = null;
let ctx = null;
let aborted = false;

// ============================================================================
// Initialization
// ============================================================================

async function init() {
    try {
        Module = await createLlamaTinyModule({
            print: (text) => self.postMessage({ type: 'log', level: 'info', data: text }),
            printErr: (text) => self.postMessage({ type: 'log', level: 'error', data: text })
        });
        
        // Initialize library
        const result = Module._llama_init();
        if (result !== 0) {
            throw new Error('Failed to initialize llama library');
        }
        
        self.postMessage({ type: 'log', level: 'info', data: 'WASM module initialized' });
        return true;
    } catch (error) {
        self.postMessage({ type: 'error', data: `Initialization failed: ${error.message}` });
        throw error;
    }
}

// ============================================================================
// Model Loading
// ============================================================================

async function loadModel(buffer, contextSize = 0) {
    // Free existing model
    if (ctx) {
        Module._llama_free_context(ctx);
        ctx = null;
    }
    if (model) {
        Module._llama_free_model(model);
        model = null;
    }
    
    // Allocate WASM memory for model
    const ptr = Module._malloc(buffer.byteLength);
    Module.HEAPU8.set(new Uint8Array(buffer), ptr);
    
    // Set up progress callback
    const progressCallback = Module.addFunction((progress) => {
        self.postMessage({
            type: 'progress',
            data: { percent: Math.round(progress * 100) }
        });
    }, 'vf');
    
    // Load model with progress
    model = Module._llama_load_model_with_progress(ptr, buffer.byteLength, contextSize, progressCallback, 0);
    
    Module.removeFunction(progressCallback);
    
    if (!model) {
        Module._free(ptr);
        const error = Module.UTF8ToString(Module._llama_get_error());
        throw new Error(`Failed to load model: ${error}`);
    }
    
    // Create context
    ctx = Module._llama_create_context(model);
    if (!ctx) {
        Module._llama_free_model(model);
        model = null;
        throw new Error('Failed to create context');
    }
    
    // Get model info
    const info = getModelInfo();
    
    self.postMessage({ type: 'log', level: 'info', data: `Model loaded: ${info.name}` });
    
    return {
        success: true,
        size: buffer.byteLength,
        info: info
    };
}

// ============================================================================
// Model Information
// ============================================================================

function getModelInfo() {
    if (!model) return null;
    
    const infoPtr = Module._llama_get_model_info_ptr(model);
    if (!infoPtr) return null;
    
    // Read model info structure
    // Note: Offsets depend on struct layout
    return {
        name: Module.UTF8ToString(Module.getValue(infoPtr, 'i32')),
        arch: Module.UTF8ToString(Module.getValue(infoPtr + 4, 'i32')),
        n_vocab: Module.getValue(infoPtr + 8, 'i32'),
        n_ctx: Module.getValue(infoPtr + 12, 'i32'),
        n_embd: Module.getValue(infoPtr + 16, 'i32'),
        n_layer: Module.getValue(infoPtr + 20, 'i32'),
        n_head: Module.getValue(infoPtr + 24, 'i32'),
        n_head_kv: Module.getValue(infoPtr + 28, 'i32'),
        n_ff: Module.getValue(infoPtr + 32, 'i32'),
        rope_freq_base: Module.getValue(infoPtr + 36, 'float'),
        model_size: Module.getValue(infoPtr + 40, 'i32')
    };
}

// ============================================================================
// Text Generation
// ============================================================================

function generate(prompt, params = {}) {
    if (!ctx) {
        throw new Error('Model not loaded');
    }
    
    aborted = false;
    
    const {
        maxTokens = 256,
        temperature = 0.7,
        topP = 0.9,
        topK = 40,
        repeatPenalty = 1.1,
        repeatLastN = 64,
        seed = 0,
        stream = true
    } = params;
    
    // Allocate prompt string
    const promptPtr = Module.allocateUTF8(prompt);
    
    // Create params struct (llama_params)
    const paramsPtr = Module._malloc(40);
    Module.setValue(paramsPtr + 0, maxTokens, 'i32');      // max_tokens
    Module.setValue(paramsPtr + 4, temperature, 'float');  // temperature
    Module.setValue(paramsPtr + 8, topP, 'float');         // top_p
    Module.setValue(paramsPtr + 12, topK, 'i32');          // top_k
    Module.setValue(paramsPtr + 16, repeatPenalty, 'float'); // repeat_penalty
    Module.setValue(paramsPtr + 20, repeatLastN, 'i32');   // repeat_last_n
    Module.setValue(paramsPtr + 24, seed, 'i64');          // seed
    Module.setValue(paramsPtr + 32, stream ? 1 : 0, 'i8'); // stream
    
    let totalTokens = 0;
    const startTime = performance.now();
    
    if (stream) {
        // Set up streaming callback
        const tokenCallback = Module.addFunction((textPtr) => {
            if (aborted) return;
            
            const text = Module.UTF8ToString(textPtr);
            totalTokens++;
            
            self.postMessage({
                type: 'token',
                data: {
                    text: text,
                    tokenCount: totalTokens
                }
            });
        }, 'vi');
        
        // Generate with streaming
        Module._llama_generate_stream(ctx, promptPtr, paramsPtr, tokenCallback, 0);
        
        Module.removeFunction(tokenCallback);
    } else {
        // Generate blocking
        const resultPtr = Module._llama_generate(ctx, promptPtr, paramsPtr);
        const result = Module.UTF8ToString(resultPtr);
        Module._llama_free_string(resultPtr);
        
        self.postMessage({
            type: 'result',
            data: { text: result }
        });
    }
    
    // Cleanup
    Module._free(promptPtr);
    Module._free(paramsPtr);
    
    const elapsed = performance.now() - startTime;
    
    return {
        totalTokens: totalTokens,
        elapsed: elapsed,
        tokensPerSecond: totalTokens / (elapsed / 1000)
    };
}

// ============================================================================
// SKZ Agent Integration
// ============================================================================

function skzGenerate(input, taskType, params = {}) {
    if (!ctx) {
        throw new Error('Model not loaded');
    }
    
    // Allocate input string
    const inputPtr = Module.allocateUTF8(input);
    
    // Create SKZ params struct
    const skzParamsPtr = Module._malloc(32);
    Module.setValue(skzParamsPtr + 0, taskType, 'i32');  // task
    Module.setValue(skzParamsPtr + 4, 0, 'i32');         // system_prompt (null)
    Module.setValue(skzParamsPtr + 8, 0.7, 'float');     // confidence_threshold
    Module.setValue(skzParamsPtr + 12, 0, 'i8');         // structured_output
    Module.setValue(skzParamsPtr + 16, 0, 'i32');        // output_schema (null)
    
    // Create generation params
    const genParamsPtr = Module._malloc(40);
    Module.setValue(genParamsPtr + 0, params.maxTokens || 256, 'i32');
    Module.setValue(genParamsPtr + 4, params.temperature || 0.7, 'float');
    Module.setValue(genParamsPtr + 8, params.topP || 0.9, 'float');
    Module.setValue(genParamsPtr + 12, params.topK || 40, 'i32');
    Module.setValue(genParamsPtr + 16, params.repeatPenalty || 1.1, 'float');
    Module.setValue(genParamsPtr + 20, 64, 'i32');
    Module.setValue(genParamsPtr + 24, 0, 'i64');
    Module.setValue(genParamsPtr + 32, 0, 'i8');
    
    // Generate
    const resultPtr = Module._skz_generate(ctx, inputPtr, skzParamsPtr, genParamsPtr);
    const result = resultPtr ? Module.UTF8ToString(resultPtr) : null;
    
    if (resultPtr) {
        Module._llama_free_string(resultPtr);
    }
    
    Module._free(inputPtr);
    Module._free(skzParamsPtr);
    Module._free(genParamsPtr);
    
    return result;
}

function skzClassify(text, categories) {
    if (!ctx) {
        throw new Error('Model not loaded');
    }
    
    // Allocate text string
    const textPtr = Module.allocateUTF8(text);
    
    // Allocate categories array
    const categoryPtrs = categories.map(cat => Module.allocateUTF8(cat));
    const categoriesPtr = Module._malloc(categoryPtrs.length * 4);
    categoryPtrs.forEach((ptr, i) => {
        Module.setValue(categoriesPtr + i * 4, ptr, 'i32');
    });
    
    // Classify
    const resultPtr = Module._skz_classify(ctx, textPtr, categoriesPtr, categories.length);
    const result = resultPtr ? Module.UTF8ToString(resultPtr) : null;
    
    if (resultPtr) {
        Module._llama_free_string(resultPtr);
    }
    
    // Cleanup
    Module._free(textPtr);
    categoryPtrs.forEach(ptr => Module._free(ptr));
    Module._free(categoriesPtr);
    
    return result;
}

function skzExtract(text, schema) {
    if (!ctx) {
        throw new Error('Model not loaded');
    }
    
    const textPtr = Module.allocateUTF8(text);
    const schemaPtr = Module.allocateUTF8(schema);
    
    const resultPtr = Module._skz_extract(ctx, textPtr, schemaPtr);
    const result = resultPtr ? Module.UTF8ToString(resultPtr) : null;
    
    if (resultPtr) {
        Module._llama_free_string(resultPtr);
    }
    
    Module._free(textPtr);
    Module._free(schemaPtr);
    
    return result;
}

// ============================================================================
// Context Management
// ============================================================================

function clearContext() {
    if (ctx) {
        Module._llama_clear_context(ctx);
    }
}

function abort() {
    aborted = true;
    if (ctx) {
        Module._llama_abort(ctx);
    }
}

function getStats() {
    if (!ctx) return null;
    
    const statsPtr = Module._llama_get_stats(ctx);
    return {
        tokens_generated: Module.getValue(statsPtr, 'i32'),
        tokens_prompt: Module.getValue(statsPtr + 4, 'i32'),
        time_prompt_ms: Module.getValue(statsPtr + 8, 'float'),
        time_generation_ms: Module.getValue(statsPtr + 12, 'float'),
        tokens_per_second: Module.getValue(statsPtr + 16, 'float')
    };
}

function getMemoryInfo() {
    if (!ctx) return null;
    
    const infoPtr = Module._llama_get_memory_info(ctx);
    return {
        model_size: Module.getValue(infoPtr, 'i32'),
        kv_cache_size: Module.getValue(infoPtr + 4, 'i32'),
        scratch_size: Module.getValue(infoPtr + 8, 'i32'),
        total_allocated: Module.getValue(infoPtr + 12, 'i32')
    };
}

// ============================================================================
// Message Handler
// ============================================================================

self.onmessage = async (e) => {
    const { type, data, id } = e.data;
    
    try {
        let result;
        
        switch (type) {
            case 'init':
                await init();
                self.postMessage({ type: 'ready', id });
                break;
                
            case 'load':
                // data can be URL string or ArrayBuffer
                let buffer;
                if (typeof data.model === 'string') {
                    // Fetch from URL
                    self.postMessage({ type: 'status', id, data: 'Downloading model...' });
                    const response = await fetch(data.model);
                    
                    if (!response.ok) {
                        throw new Error(`Failed to fetch model: ${response.status}`);
                    }
                    
                    const total = parseInt(response.headers.get('content-length') || '0');
                    const reader = response.body.getReader();
                    const chunks = [];
                    let loaded = 0;
                    
                    while (true) {
                        const { done, value } = await reader.read();
                        if (done) break;
                        
                        chunks.push(value);
                        loaded += value.length;
                        
                        if (total > 0) {
                            self.postMessage({
                                type: 'download_progress',
                                id,
                                data: { loaded, total, percent: Math.round(loaded / total * 100) }
                            });
                        }
                    }
                    
                    buffer = new Uint8Array(loaded);
                    let offset = 0;
                    for (const chunk of chunks) {
                        buffer.set(chunk, offset);
                        offset += chunk.length;
                    }
                    buffer = buffer.buffer;
                } else {
                    buffer = data.model;
                }
                
                self.postMessage({ type: 'status', id, data: 'Loading model...' });
                result = await loadModel(buffer, data.contextSize || 0);
                self.postMessage({ type: 'loaded', id, data: result });
                break;
                
            case 'generate':
                const stats = generate(data.prompt, data.params);
                self.postMessage({ type: 'done', id, data: stats });
                break;
                
            case 'skz_generate':
                result = skzGenerate(data.input, data.taskType, data.params);
                self.postMessage({ type: 'result', id, data: { text: result } });
                break;
                
            case 'skz_classify':
                result = skzClassify(data.text, data.categories);
                self.postMessage({ type: 'result', id, data: { classification: result } });
                break;
                
            case 'skz_extract':
                result = skzExtract(data.text, data.schema);
                self.postMessage({ type: 'result', id, data: { extracted: result } });
                break;
                
            case 'clear':
                clearContext();
                self.postMessage({ type: 'cleared', id });
                break;
                
            case 'abort':
                abort();
                self.postMessage({ type: 'aborted', id });
                break;
                
            case 'info':
                result = getModelInfo();
                self.postMessage({ type: 'info', id, data: result });
                break;
                
            case 'stats':
                result = getStats();
                self.postMessage({ type: 'stats', id, data: result });
                break;
                
            case 'memory':
                result = getMemoryInfo();
                self.postMessage({ type: 'memory', id, data: result });
                break;
                
            default:
                throw new Error(`Unknown message type: ${type}`);
        }
    } catch (error) {
        self.postMessage({
            type: 'error',
            id,
            data: error.message || String(error)
        });
    }
};

// Report ready
self.postMessage({ type: 'worker_ready' });
